### ISSUE TITLE
Why epsilon can be larger than 1?

### ISSUE THREAD

**Issue by sjyjytu** [MadryLab/mnist_challenge#13]
To whom it may concern,
I have read your paper Towards Deep Learning Models Resistant to Adversarial Attacks and try the code provided in this project.
Thanks for your good job! However, I still have some questions about the paper and the code.
Some experiments mentioned in your paper claimed that epsilon was equal to 8, but I find every pixel to be perturbed is clipped to 0 to 1 according to the code. And when I set epsilon to some number that is larger than 1, I can not get the accuracy you mentioned in the paper. So why can epsilon be set larger than 1? Do I have some misunderstandings about the paper?
Looking forward to your reply.
Best Wishes,
May, 22th by JY

**Comment by dtsip** [comment]
You are right, since valid pixel values are from 0 to 1, we clip the perturbation to that range at every step.

The value 8 that you are referring to corresponds to the [CIFAR10 dataset](https://github.com/MadryLab/cifar10_challenge) where valid pixel values are from 0 to 255. So 8 is actually quite small.

Let me know if that does not make sense.

**Comment by sjyjytu** [comment]
okay, thank you very much!

**Comment by syf-fgnb** [comment]
So why do you use epsilon=8/255 for CIFAR10 but epsilon=0.3 for MNIST rather than use epsilon=8/255 for both datasets? Does 0.3 for MNIST means 0.3/255? If not, why do you use such large epsilon (0.3>>8/255) on MNIST?

Please forgive me for such a stupid question. I'm a greenhand in this area.

**Comment by dtsip** [comment]
We do use a different epsilon for each dataset---for MNIST we use 0.3/1 and for CIFAR10 8/255. The reason is that these datasets are quite different so the epsilon values that we can be robust to are also different. Specifically, MNIST consists of black-and-white images, so a perturbation of 0.3 cannot change a white pixel to black and vice-versa (which is why we are able to learn robust classifiers after all). In contrast, for CIFAR10, pixels lie in a wider range of values, while the image is 3-dimensional (RGB). As a result, the perturbation needed to actually change the class of an image is much smaller (in Figure 8 of https://arxiv.org/abs/1805.12152 you can see how perturbations of 0.125/1 on CIFAR10 completely change the content of the image).

**Comment by syf-fgnb** [comment]
I get it. Thank you very much!

**Comment by bieyl** [comment]
@sjyjytu  In the paper(Generating Adversarial Examples with Adversarial Networks),there is a full objective can be expressed as L = Lfadv + αLGAN + βLhinge. But i can not find in this code. could you tell me if you know? Thanks.
