### ISSUE TITLE
(Not an issue) Request to keep the challenge open

### ISSUE THREAD

**Issue by akarshzingade** [MadryLab/mnist_challenge#2]
Hi. I feel that you should keep this challenge open and accept submissions even though you have released your secret model. Any particular reason for closing this on Oct 15th?

**Comment by dtsip** [comment]
Yes, we plan to keep the challenge open. However, since we have now released the secret model, this is no longer a _black-box_ challenge, but a _white-box_ one. Therefore we need to setup a separate leaderboard and seed it with a few entries. We plan to do this within the next week. Of course if you want to submit an attack before then, you are free to do so.

**Comment by dtsip** [comment]
The leaderboard for the white-box part of the challenge is up. Your submissions are welcome!
